### ISSUE TITLE
Use Turbopack or SWC for transpiling electron app + cleanup config files

### ISSUE THREAD

**Issue by himanshu-dixit** [crusher-dev/crusher#336]
https://github.com/crusher-dev/crusher/tree/master/packages/electron-app/webpack di contains config for building crusher electron app

We build for renderer process and electron-main process. 

**Tasks**
:- use swc-loader instead of ts-loader. File for example(https://github.com/crusher-dev/crusher/blob/master/packages/electron-app/webpack/webpack.renderer.ts#L32)
:- Cleanup webpack config files

**Comment by arpitBhalla** [comment]
@himanshu-dixit can I work on it?

**Comment by himanshu-dixit** [comment]
@arpitBhalla :- assigned it to you
